# Generated by Django 3.0.2 on 2021-11-25 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=13)),
                ('observ', models.CharField(blank=True, max_length=100)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conta.Conta')),
            ],
        ),
    ]
