# Generated by Django 3.0.2 on 2021-12-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimento',
            options={'ordering': ('data',)},
        ),
    ]
