# Generated by Django 3.0.2 on 2021-12-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0002_auto_20211208_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimento',
            options={'ordering': ('data', 'conta')},
        ),
    ]
