# Generated by Django 4.0.1 on 2022-01-23 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meiopagamento', '0002_alter_meiopagamento_nome'),
        ('movimento', '0003_auto_20211215_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='meiopagamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='meiopagamento.meiopagamento'),
            preserve_default=False,
        ),
    ]
