# Generated by Django 4.0.1 on 2022-01-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0004_movimento_meiopagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='documento',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
