# Generated by Django 4.0.1 on 2022-01-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0005_movimento_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='documento',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
