# Generated by Django 4.0.1 on 2022-02-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimento', '0007_movimento_id_competencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimento',
            old_name='id_competencia',
            new_name='competencia',
        ),
    ]
