# Generated by Django 3.0.2 on 2021-11-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0006_remove_categoria_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
