# Generated by Django 3.0.2 on 2021-11-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0008_auto_20211122_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Receita'), (2, 'Despesa')], default=1),
        ),
    ]
