# Generated by Django 4.0 on 2022-01-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechamento',
            name='nome',
        ),
    ]
