# Generated by Django 4.0.1 on 2022-01-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechamento',
            options={'ordering': ['data']},
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='nome',
        ),
        migrations.AlterField(
            model_name='fechamento',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fechamento',
            name='fechado',
            field=models.BooleanField(choices=[(True, 'Fechado'), (False, 'Aberto')], default=False),
        ),
    ]
