# Generated by Django 4.0 on 2022-01-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0002_remove_fechamento_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechamento',
            name='mes_ano',
        ),
        migrations.AddField(
            model_name='fechamento',
            name='ano',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fechamento',
            name='mes',
            field=models.IntegerField(null=True),
        ),
    ]
