# Generated by Django 4.0 on 2022-01-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0003_remove_fechamento_mes_ano_fechamento_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamento',
            name='ano',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='fechamento',
            name='mes',
            field=models.IntegerField(default=1),
        ),
    ]
