# Generated by Django 4.0 on 2022-01-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0004_alter_fechamento_ano_alter_fechamento_mes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechamento',
            options={'ordering': ('ano', 'mes')},
        ),
        migrations.AlterField(
            model_name='fechamento',
            name='ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fechamento',
            name='entradas',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='fechamento',
            name='fechado',
            field=models.BooleanField(choices=[(True, 'Fechado'), (False, 'Aberto')], default=False),
        ),
        migrations.AlterField(
            model_name='fechamento',
            name='mes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fechamento',
            name='saidas',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='fechamento',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='fechamento',
            name='saldo_anterior',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterUniqueTogether(
            name='fechamento',
            unique_together={('ano', 'mes')},
        ),
    ]
