# Generated by Django 4.0 on 2022-01-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0005_alter_fechamento_options_alter_fechamento_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamento',
            name='entradas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='fechamento',
            name='saidas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='fechamento',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
    ]
