# Generated by Django 4.0 on 2022-01-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0006_alter_fechamento_entradas_alter_fechamento_saidas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamento',
            name='data',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
