# Generated by Django 4.0.1 on 2022-01-12 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fechamento', '0007_fechamento_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechamento',
            options={'ordering': ['data']},
        ),
        migrations.AlterUniqueTogether(
            name='fechamento',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='fechamento',
            name='mes',
        ),
    ]
