# Generated by Django 4.0.1 on 2022-01-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeioPagamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(db_index=True, max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
