# Generated by Django 4.0.1 on 2022-01-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meiopagamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meiopagamento',
            name='nome',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
